import { API_CONFIG } from '@/core/config/api.config';

export const USER_TYPE_CONFIG: Record<string, any> = {
  SUPER_ADMIN: {
    title: 'Super Admins',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.SUPER_ADMIN,
    entityLabel: 'Super Admin',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone number', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.CATEGORIES,
    navPath: '/dashboard/super-admin-users',
    dependencies: ['generalDivisions'],
  },
  HEALTH_DIRECTORATE: {
    title: 'Health Directorate Users',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.HEALTH_DIRECTORATE,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone Number', sortable: true },
      { field: 'directorate', header: 'Directorate', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HEALTH_DIRECTORATE,
    navPath: '/dashboard/health-directorate-users',
    dependencies: ['directorates', 'generalDivisions'],
  },
  HEALTH_DIVISION: {
    title: 'Health Division Users',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.HEALTH_DIVISION,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone Number', sortable: true },
      { field: 'directorate', header: 'Directorate', sortable: true },
      { field: 'division', header: 'Health Division', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HEALTH_DIVISION,
    navPath: '/dashboard/health-division-users',
    dependencies: ['directorates', 'healthDivisions', 'generalDivisions'],
  },
  HOSPITAL: {
    title: 'Hospital Users',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.HOSPITAL,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone Number', sortable: true },
      { field: 'directorate', header: 'Directorate', sortable: true },
      { field: 'division', header: 'Health Division', sortable: true },
      { field: 'hospital', header: 'Hospital', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HOSPITAL,
    navPath: '/dashboard/hospitals-users',
    dependencies: ['directorates', 'healthDivisions', 'hospitals', 'generalDivisions'],
  },
  AUTHORITY: {
    title: 'Authority Users',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.AUTHORITY,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Username', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone', sortable: true },
      { field: 'authority', header: 'Authority', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.AUTHORITY,
    navPath: '/dashboard/authorities-users',
    dependencies: ['authorities', 'generalDivisions'],
  },
  AUTHORITY_HOSPITAL: {
    title: "Authority's Hospital Users",
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.AUTHORITY_HOSPITAL,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Username', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone', sortable: true },
      { field: 'authority', header: 'Authority', sortable: true },
      { field: 'hospital', header: 'Hospital', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HOSPITAL,
    navPath: '/dashboard/authorities-hospitals-users',
    dependencies: ['authorities', 'hospitals', 'generalDivisions'],
  },
};
