import { IFormField } from '@shared/models/form-field.model';
import { Validators } from '@angular/forms';

export const getHospitalFormConfig = (
  directorates: { label: string; value: any }[],
  healthDivisions: { label: string; value: any }[],
  generalDivisions: { label: string; value: any }[],
  isDirectoratesLoading: boolean = false,
  isHealthDivisionsLoading: boolean = false,
  isDivisionsLoading: boolean = false,
): IFormField[] => [
    {
      key: 'name',
      label: 'Hospital Name',
      type: 'text',
      placeholder: 'Enter hospital name',
      validators: [Validators.required],
      colSpan: 'col-span-full',
    },
    {
      key: 'health_directorate_id',
      label: 'Health Directorate',
      type: 'select',
      placeholder: 'Select Directorate',
      options: directorates,
      validators: [Validators.required],
      colSpan: 'col-span-1',
      filter: true,
      virtualScroll: true,
      loading: isDirectoratesLoading,
    },
    {
      key: 'health_division_id',
      label: 'Health Division',
      type: 'select',
      placeholder: 'Select Health Division',
      options: healthDivisions,
      validators: [Validators.required],
      colSpan: 'col-span-1',
      filter: true,
      virtualScroll: true,
      loading: isHealthDivisionsLoading,
    },
    {
      key: 'division_id',
      label: 'General Division',
      type: 'select',
      placeholder: 'Select General Division',
      options: generalDivisions,
      validators: [Validators.required],
      colSpan: 'col-span-1',
      filter: true,
      virtualScroll: true,
      loading: isDivisionsLoading,
    },
  ];
