import { API_CONFIG } from '@/core/config/api.config';
import { Validators } from '@angular/forms';

export const ENTITY_TYPE_CONFIG: Record<string, any> = {
  HEALTH_DIRECTORATE: {
    title: 'Health Directorates',
    entityLabel: 'Directorate',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HEALTH_DIRECTORATE,
    navPath: '/health-directorate',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle' },
    ],
    formFields: () => [
      {
        key: 'name',
        label: 'Directorate Name',
        type: 'text',
        placeholder: 'Enter directorate name',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
    ],
  },
  HEALTH_DIVISION: {
    title: 'Health Divisions',
    entityLabel: 'Division',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HEALTH_DIVISION,
    navPath: '/health-division',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'directorate', header: 'Directorate', sortable: true, type: 'text' },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Division Name',
        type: 'text',
        placeholder: 'Enter division name',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'health_directorate_id',
        label: 'Health Directorate',
        type: 'select',
        placeholder: 'Select health directorate',
        options: deps.directorates || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        loading: deps.isDirectoratesLoading,
      },
    ],
    dependencies: ['directorates'],
  },
  HOSPITAL: {
    title: 'Hospitals',
    entityLabel: 'Hospital',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HOSPITAL,
    parent_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HEALTH_DIVISION,
    navPath: '/hospitals',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'division', header: 'Division', sortable: true, type: 'text' },
      { field: 'directorate', header: 'Directorate', sortable: true, type: 'text' },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Hospital Name',
        type: 'text',
        placeholder: 'Enter hospital name',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'health_directorate_id',
        label: 'Health Directorate',
        type: 'select',
        placeholder: 'Select Directorate',
        options: deps.directorates || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        loading: deps.isDirectoratesLoading,
      },
      {
        key: 'health_division_id',
        label: 'Health Division',
        type: 'select',
        placeholder: 'Select Health Division',
        options: deps.healthDivisions || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        loading: deps.isHealthDivisionsLoading,
        dependsOn: 'health_directorate_id',
      },
      {
        key: 'category_ids',
        label: 'General Division',
        type: 'multiselect',
        placeholder: 'Select General Divisions',
        options: deps.generalDivisions || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        loading: deps.isGeneralDivisionsLoading,
      },
    ],
    dependencies: ['directorates', 'healthDivisions', 'generalDivisions'],
  },
  AUTHORITY: {
    title: 'Authorities',
    entityLabel: 'Authority',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.AUTHORITY,
    navPath: '/authorities',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle' },
    ],
    formFields: () => [
      {
        key: 'name',
        label: 'Authority Name',
        type: 'text',
        placeholder: 'Enter authority name',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
    ],
  },
  AUTHORITY_HOSPITAL: {
    title: "Authority's Hospitals",
    entityLabel: 'Authority Hospital',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HOSPITAL,
    parent_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.AUTHORITY,
    navPath: '/authorities-hospitals',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'authority', header: 'Authority', sortable: true, type: 'text' },
      { field: 'division', header: 'Division', sortable: true, type: 'text' },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Hospital Name',
        type: 'text',
        placeholder: 'Enter name',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'authority_id',
        label: 'Authority',
        type: 'select',
        placeholder: 'Select Authority',
        options: deps.authorities || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        loading: deps.isAuthoritiesLoading,
      },
      {
        key: 'category_ids',
        label: 'General Division',
        type: 'multiselect',
        placeholder: 'Select Divisions',
        options: deps.generalDivisions || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        loading: deps.isGeneralDivisionsLoading,
      },
    ],
    dependencies: ['authorities', 'generalDivisions'],
  },
  DIVISION: {
    title: 'Divisions',
    entityLabel: 'Division',
    endpoint: API_CONFIG.ENDPOINTS.CATEGORIES,
    navPath: '/divisions',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle' },
    ],
    formFields: () => [
      {
        key: 'name',
        label: 'Division Name',
        type: 'text',
        placeholder: 'Enter division name',
        validators: [Validators.required],
        colSpan: 'col-span-full',
      },
    ],
  },
};
