import { API_CONFIG } from '@/core/config/api.config';
import { Validators } from '@angular/forms';

export const ENTITY_TYPE_CONFIG: Record<string, any> = {
  DIVISION: {
    title: 'Divisions',
    entityLabel: 'Division',
    endpoint: API_CONFIG.ENDPOINTS.CATEGORIES,
    navPath: '/dashboard/divisions',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: () => [
      {
        key: 'name',
        label: 'Division Name',
        type: 'text',
        placeholder: 'Enter division name...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
    ],
  },
  HEALTH_DIRECTORATE: {
    title: 'Health Directorates',
    entityLabel: 'Directorate',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HEALTH_DIRECTORATE,
    navPath: '/dashboard/health-directorate',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: () => [
      {
        key: 'name',
        label: 'Health Directorate Name',
        type: 'text',
        placeholder: 'Enter health directorate...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
    ],
  },
  HEALTH_DIVISION: {
    title: 'Health Divisions',
    entityLabel: 'Division',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HEALTH_DIVISION,
    navPath: '/dashboard/health-division',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'directorate', header: 'Directorate', sortable: true, type: 'text' },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Health Division Name',
        type: 'text',
        placeholder: 'Enter health division...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'health_directorate_id',
        label: 'Health Directorate',
        type: 'select',
        placeholder: 'Select health directorate...',
        options: deps.directorates || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isDirectoratesLoading,
      },
    ],
    dependencies: ['directorates'],
  },
  HOSPITAL: {
    title: 'Hospitals',
    entityLabel: 'Hospital',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HOSPITAL,
    parent_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HEALTH_DIVISION,
    navPath: '/dashboard/hospitals',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'categories', header: 'Division', sortable: true, type: 'text' },
      { field: 'directorate', header: 'Directorate', sortable: true, type: 'text' },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Hospital Name',
        type: 'text',
        placeholder: 'Enter hospital name...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'health_directorate_id',
        label: 'Health Directorate Name',
        type: 'select',
        placeholder: 'Select health directorate name...',
        options: deps.directorates || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isDirectoratesLoading,
      },
      {
        key: 'health_division_id',
        label: 'Health Division Name',
        type: 'select',
        placeholder: 'Select health division name...',
        options: deps.healthDivisions || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isHealthDivisionsLoading,
        dependsOn: 'health_directorate_id',
      },
      {
        key: 'category_ids',
        label: 'Division Name',
        subLable: '(All Selected by Default)',
        type: 'multiselect',
        placeholder: 'Select Division Name...',
        options: deps.generalDivisions || [],
        validators: [],
        virtualScroll: true,
        colSpan: 'col-span-1',
        filter: true,
        loading: deps.isGeneralDivisionsLoading,
      },
    ],
    dependencies: ['directorates', 'healthDivisions', 'generalDivisions'],
  },
  AUTHORITY: {
    title: 'Authorities',
    entityLabel: 'Authority',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.AUTHORITY,
    navPath: '/dashboard/authorities',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: () => [
      {
        key: 'name',
        label: 'Authority Name',
        type: 'text',
        placeholder: 'Enter authority name',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
    ],
  },
  AUTHORITY_HOSPITAL: {
    title: "Authority's Hospitals",
    entityLabel: 'Authority Hospital',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.HOSPITAL,
    parent_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.AUTHORITY,
    navPath: '/dashboard/authorities-hospitals',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'authority', header: 'Authority', sortable: true, type: 'text' },
      { field: 'categories', header: 'Division', sortable: true, type: 'text' },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Hospital Authority Name',
        type: 'text',
        placeholder: 'Enter hospital authority name...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'authority_id',
        label: 'Authority Name',
        type: 'select',
        placeholder: 'Select authority name...',
        options: deps.authorities || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isAuthoritiesLoading,
      },
      {
        key: 'category_ids',
        label: 'Divison Name',
        type: 'multiselect',
        subLable: '(All Selected by Default)',
        placeholder: 'Select Division name...',
        options: deps.generalDivisions || [],
        validators: [],
        colSpan: 'col-span-1',
        virtualScroll: true,
        filter: true,
        loading: deps.isGeneralDivisionsLoading,
      },
    ],
    dependencies: ['authorities', 'generalDivisions'],
  },
};
